import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import Nav from "../components/Nav";

import CartIcon from "../components/CartIcon";

import "./globals.css";
import { Quicksand, Bangers, Roboto_Condensed } from "next/font/google";
import CartProvider from "@/context/CartContext";

import CartMobile from "../components/CartMobile";

import CartDesktop from "../components/CartDesktop";

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-quicksand",
});

const bangers = Bangers({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bangers",
});

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-robotoCondensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CartProvider>
      <html lang="en">
        <body
          className={`${quicksand.variable} ${bangers.variable} ${robotoCondensed.variable} overflow-x-hidden `}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <CartMobile />
            <Nav />
            <CartIcon />
            <CartDesktop />

            {children}
          </ThemeProvider>
        </body>
      </html>
    </CartProvider>
  );
}
